# Generated by Django 5.2.13 on 2026-05-05 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_icono', models.CharField(choices=[('bootstrap', 'Bootstrap Icon'), ('imagen', 'Imagen / SVG / GIF'), ('lottie', 'Lottie JSON')], default='bootstrap', max_length=20)),
                ('icono_bootstrap', models.CharField(blank=True, help_text='Ejemplo: bi-calendar-star-fill, bi-music-note-beamed', max_length=80)),
                ('icono_archivo', models.FileField(blank=True, help_text='Sube SVG, PNG, WebP, GIF o JSON Lottie si no usarás Bootstrap Icons.', upload_to='eventos/categorias/iconos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de evento',
                'verbose_name_plural': 'Categorías de eventos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('mixta', 'Mixta')], default='presencial', max_length=20)),
                ('lugar', models.CharField(blank=True, help_text='Ejemplo: Plaza de Armas, Coliseo, Centro Cultural, explanada, auditorio.', max_length=180)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('tipo_costo', models.CharField(choices=[('gratis', 'Gratis'), ('pagado', 'Pagado'), ('consultar', 'Consultar')], default='consultar', max_length=20)),
                ('precio_desde', models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo referencial en soles, si aplica.', max_digits=8, null=True, verbose_name='Precio desde')),
                ('precio_hasta', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo referencial en soles, si aplica.', max_digits=8, null=True, verbose_name='Precio hasta')),
                ('organizador', models.CharField(blank=True, max_length=180)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('recomendaciones', models.TextField(blank=True, help_text='Consejos para asistentes: llegar temprano, llevar abrigo, restricciones, etc.')),
                ('publico_objetivo', models.CharField(blank=True, help_text='Ejemplo: público general, familias, niños, turistas, jóvenes.', max_length=160)),
                ('notas', models.TextField(blank=True, help_text='Información adicional interna o pública.')),
                ('imagen_principal', models.ImageField(blank=True, upload_to='eventos/principales/')),
                ('texto_alt_imagen', models.CharField(blank=True, max_length=180)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_principales', to='eventos.categoriaevento', verbose_name='Categoría principal')),
                ('categorias_secundarias', models.ManyToManyField(blank=True, related_name='eventos_secundarios', to='eventos.categoriaevento', verbose_name='Categorías secundarias')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='ubicaciones.distrito')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='ubicaciones.localidad')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='eventos/galeria/')),
                ('titulo', models.CharField(blank=True, max_length=160)),
                ('texto_alt', models.CharField(blank=True, max_length=180)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Imagen de evento',
                'verbose_name_plural': 'Imágenes de eventos',
                'ordering': ['evento__nombre', 'orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.UniqueConstraint(fields=('nombre', 'fecha_inicio'), name='unique_evento_nombre_fecha_inicio'),
        ),
    ]
