# Generated by Django 5.2.13 on 2026-05-03 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficial', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('codigo_inei', models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre_oficial'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficial', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('codigo_inei', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provincias', to='ubicaciones.departamento')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['departamento__nombre_oficial', 'nombre_oficial'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficial', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('codigo_inei', models.CharField(max_length=6, unique=True)),
                ('codigo_api', models.CharField(blank=True, max_length=20)),
                ('api_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distritos', to='ubicaciones.provincia')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['provincia__departamento__nombre_oficial', 'provincia__nombre_oficial', 'nombre_oficial'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160)),
                ('tipo', models.CharField(choices=[('Capital distrital', 'Capital distrital'), ('Ciudad', 'Ciudad'), ('Centro poblado', 'Centro poblado'), ('Zona', 'Zona'), ('Sector', 'Sector'), ('Referencia', 'Referencia')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidades', to='ubicaciones.distrito')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['distrito__provincia__departamento__nombre_oficial', 'distrito__provincia__nombre_oficial', 'distrito__nombre_oficial', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('distrito', 'nombre'), name='unique_localidad_nombre_distrito'), models.UniqueConstraint(fields=('distrito', 'slug'), name='unique_localidad_slug_distrito')],
            },
        ),
        migrations.AddConstraint(
            model_name='provincia',
            constraint=models.UniqueConstraint(fields=('departamento', 'nombre_oficial'), name='unique_provincia_nombre_departamento'),
        ),
        migrations.AddConstraint(
            model_name='provincia',
            constraint=models.UniqueConstraint(fields=('departamento', 'slug'), name='unique_provincia_slug_departamento'),
        ),
        migrations.AddConstraint(
            model_name='distrito',
            constraint=models.UniqueConstraint(fields=('provincia', 'nombre_oficial'), name='unique_distrito_nombre_provincia'),
        ),
        migrations.AddConstraint(
            model_name='distrito',
            constraint=models.UniqueConstraint(fields=('provincia', 'slug'), name='unique_distrito_slug_provincia'),
        ),
    ]
