# Generated by Django 5.2.13 on 2026-05-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(help_text='Ejemplo: Historia · Cultura · Naturaleza', max_length=100)),
                ('titulo_principal', models.CharField(help_text='Ejemplo: Descubre lugares', max_length=150)),
                ('titulo_resaltado', models.CharField(help_text='Ejemplo: con identidad', max_length=150)),
                ('descripcion', models.TextField()),
                ('tipo_archivo', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('gif', 'GIF')], default='image', max_length=10)),
                ('archivo', models.FileField(help_text='Acepta imagen, video o gif', upload_to='home/hero/')),
                ('poster_video', models.ImageField(blank=True, help_text='Imagen previa para videos (recomendado)', null=True, upload_to='home/hero/posters/')),
                ('texto_alt', models.CharField(blank=True, help_text='Para accesibilidad de imágenes/gifs', max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('intervalo_ms', models.PositiveIntegerField(default=5500, help_text='Tiempo en milisegundos que dura el slide')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slide del Hero',
                'verbose_name_plural': 'Slides del Hero',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
