# Generated by Django 5.2.13 on 2026-05-04 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_icono', models.CharField(choices=[('bootstrap', 'Bootstrap Icon'), ('imagen', 'Imagen / SVG / GIF'), ('lottie', 'Lottie JSON')], default='bootstrap', max_length=20)),
                ('icono_bootstrap', models.CharField(blank=True, help_text='Ejemplo: bi-cup-hot-fill', max_length=80)),
                ('icono_archivo', models.FileField(blank=True, help_text='Sube SVG, PNG, WebP, GIF o JSON Lottie si no usarás Bootstrap Icons.', upload_to='establecimientos/iconos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de establecimiento',
                'verbose_name_plural': 'Categorías de establecimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('aplica_a', models.CharField(choices=[('todos', 'Todos'), ('restaurante', 'Restaurantes'), ('hospedaje', 'Hospedajes')], default='todos', max_length=20)),
                ('tipo_icono', models.CharField(choices=[('bootstrap', 'Bootstrap Icon'), ('imagen', 'Imagen / SVG / GIF'), ('lottie', 'Lottie JSON')], default='bootstrap', max_length=20)),
                ('icono_bootstrap', models.CharField(blank=True, help_text='Ejemplo: bi-wifi', max_length=80)),
                ('icono_archivo', models.FileField(blank=True, help_text='Sube SVG, PNG, WebP, GIF o JSON Lottie si no usarás Bootstrap Icons.', upload_to='establecimientos/servicios/iconos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio de establecimiento',
                'verbose_name_plural': 'Servicios de establecimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('restaurante', 'Restaurante'), ('hospedaje', 'Hospedaje')], max_length=20)),
                ('nombre', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('rango_precio', models.CharField(choices=[('economico', 'Económico'), ('moderado', 'Moderado'), ('alto', 'Alto'), ('consultar', 'Consultar')], default='consultar', max_length=20)),
                ('precio_desde', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('imagen_principal', models.ImageField(blank=True, upload_to='establecimientos/principales/')),
                ('texto_alt_imagen', models.CharField(blank=True, max_length=180)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establecimientos_principales', to='establecimientos.categoriaestablecimiento', verbose_name='Categoría principal')),
                ('categorias_secundarias', models.ManyToManyField(blank=True, help_text='Especialidades adicionales del establecimiento.', related_name='establecimientos_secundarios', to='establecimientos.categoriaestablecimiento', verbose_name='Categorías secundarias')),
                ('servicios', models.ManyToManyField(blank=True, help_text='Servicios o amenidades que ofrece el establecimiento.', related_name='establecimientos', to='establecimientos.servicioestablecimiento', verbose_name='Servicios')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='establecimientos/galeria/')),
                ('titulo', models.CharField(blank=True, max_length=160)),
                ('texto_alt', models.CharField(blank=True, max_length=180)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='establecimientos.establecimiento')),
            ],
            options={
                'verbose_name': 'Imagen de establecimiento',
                'verbose_name_plural': 'Imágenes de establecimientos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SucursalEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Sucursal principal, Sucursal Huallayco, Sucursal Cayhuayna', max_length=160)),
                ('slug', models.SlugField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('horario_atencion', models.CharField(blank=True, max_length=180)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales_establecimientos', to='ubicaciones.distrito')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='establecimientos.establecimiento')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales_establecimientos', to='ubicaciones.localidad')),
            ],
            options={
                'verbose_name': 'Sucursal de establecimiento',
                'verbose_name_plural': 'Sucursales de establecimientos',
                'ordering': ['establecimiento__nombre', '-es_principal', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('establecimiento', 'nombre'), name='unique_sucursal_nombre_por_establecimiento'), models.UniqueConstraint(fields=('establecimiento', 'slug'), name='unique_sucursal_slug_por_establecimiento'), models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('establecimiento',), name='unique_sucursal_principal_por_establecimiento')],
            },
        ),
    ]
