# Generated by Django 5.2.13 on 2026-05-04 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoSucursalEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contacto', models.CharField(choices=[('telefono', 'Teléfono'), ('celular', 'Celular'), ('whatsapp', 'WhatsApp'), ('correo', 'Correo'), ('reservas', 'Reservas'), ('atencion_cliente', 'Atención al cliente'), ('administracion', 'Administración')], max_length=30)),
                ('etiqueta', models.CharField(blank=True, help_text='Ejemplo: Reservas, Atención al cliente, Administración, Celular principal.', max_length=80)),
                ('valor', models.CharField(help_text='Número, correo o dato de contacto.', max_length=120)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='establecimientos.sucursalestablecimiento')),
            ],
            options={
                'verbose_name': 'Contacto de sucursal',
                'verbose_name_plural': 'Contactos de sucursales',
                'ordering': ['sucursal__establecimiento__nombre', 'sucursal__nombre', 'orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('sucursal', 'valor'), name='unique_contacto_valor_por_sucursal'), models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('sucursal', 'tipo_contacto'), name='unique_contacto_principal_por_tipo_sucursal')],
            },
        ),
    ]
