# Generated by Django 5.2.13 on 2026-05-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0002_contactosucursalestablecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='precio_hasta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo referencial en soles. Ejemplo: plato de mayor precio o habitación de mayor precio.', max_digits=8, null=True, verbose_name='Precio hasta'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='precio_desde',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo referencial en soles. Ejemplo: plato más económico o habitación más económica.', max_digits=8, null=True, verbose_name='Precio desde'),
        ),
    ]
