# Generated by Django 5.2.13 on 2026-05-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0003_establecimiento_precio_hasta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='tipo',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('alojamiento', 'Alojamiento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicioestablecimiento',
            name='aplica_a',
            field=models.CharField(choices=[('todos', 'Todos'), ('restaurante', 'Restaurantes'), ('alojamiento', 'Alojamientos')], default='todos', max_length=20),
        ),
    ]
