# Generated by Django 5.2.13 on 2026-05-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_icono', models.CharField(choices=[('bootstrap', 'Bootstrap Icon'), ('imagen', 'Imagen / SVG / GIF'), ('lottie', 'Lottie JSON')], default='bootstrap', max_length=20)),
                ('icono_bootstrap', models.CharField(blank=True, help_text='Ejemplo: bi-geo-alt-fill, bi-tree-fill, bi-bank', max_length=80)),
                ('icono_archivo', models.FileField(blank=True, help_text='Sube SVG, PNG, WebP, GIF o JSON Lottie si no usarás Bootstrap Icons.', upload_to='turismo/categorias/iconos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de lugar turístico',
                'verbose_name_plural': 'Categorías de lugares turísticos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioLugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_icono', models.CharField(choices=[('bootstrap', 'Bootstrap Icon'), ('imagen', 'Imagen / SVG / GIF'), ('lottie', 'Lottie JSON')], default='bootstrap', max_length=20)),
                ('icono_bootstrap', models.CharField(blank=True, help_text='Ejemplo: bi-p-square-fill, bi-person-wheelchair, bi-binoculars-fill', max_length=80)),
                ('icono_archivo', models.FileField(blank=True, help_text='Sube SVG, PNG, WebP, GIF o JSON Lottie si no usarás Bootstrap Icons.', upload_to='turismo/servicios/iconos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio de lugar turístico',
                'verbose_name_plural': 'Servicios de lugares turísticos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('historia', models.TextField(blank=True, help_text='Información histórica o cultural del lugar, si aplica.')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('horario_visita', models.CharField(blank=True, max_length=180)),
                ('tipo_costo', models.CharField(choices=[('gratis', 'Gratis'), ('pagado', 'Pagado'), ('consultar', 'Consultar')], default='consultar', max_length=20)),
                ('precio_desde', models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo referencial en soles, si aplica.', max_digits=8, null=True, verbose_name='Precio desde')),
                ('precio_hasta', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo referencial en soles, si aplica.', max_digits=8, null=True, verbose_name='Precio hasta')),
                ('tiempo_visita_estimado', models.CharField(blank=True, help_text='Ejemplo: 1 hora, medio día, 2 horas.', max_length=120)),
                ('dificultad', models.CharField(choices=[('no_aplica', 'No aplica'), ('facil', 'Fácil'), ('moderada', 'Moderada'), ('dificil', 'Difícil')], default='no_aplica', max_length=20)),
                ('recomendaciones', models.TextField(blank=True, help_text='Consejos para el turista: ropa, horario ideal, clima, seguridad, etc.')),
                ('como_llegar', models.TextField(blank=True, help_text='Indicaciones generales para llegar al lugar.')),
                ('imagen_principal', models.ImageField(blank=True, upload_to='turismo/lugares/principales/')),
                ('texto_alt_imagen', models.CharField(blank=True, max_length=180)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lugares_principales', to='turismo.categorialugarturistico', verbose_name='Categoría principal')),
                ('categorias_secundarias', models.ManyToManyField(blank=True, related_name='lugares_secundarios', to='turismo.categorialugarturistico', verbose_name='Categorías secundarias')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lugares_turisticos', to='ubicaciones.distrito')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lugares_turisticos', to='ubicaciones.localidad')),
                ('servicios', models.ManyToManyField(blank=True, related_name='lugares', to='turismo.serviciolugarturistico', verbose_name='Servicios disponibles')),
            ],
            options={
                'verbose_name': 'Lugar turístico',
                'verbose_name_plural': 'Lugares turísticos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenLugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='turismo/lugares/galeria/')),
                ('titulo', models.CharField(blank=True, max_length=160)),
                ('texto_alt', models.CharField(blank=True, max_length=180)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='turismo.lugarturistico')),
            ],
            options={
                'verbose_name': 'Imagen de lugar turístico',
                'verbose_name_plural': 'Imágenes de lugares turísticos',
                'ordering': ['lugar__nombre', 'orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='lugarturistico',
            constraint=models.UniqueConstraint(fields=('distrito', 'nombre'), name='unique_lugar_nombre_distrito'),
        ),
    ]
