# Generated by Django 5.2.13 on 2026-05-05 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicioTurista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_icono', models.CharField(choices=[('bootstrap', 'Bootstrap Icon'), ('imagen', 'Imagen / SVG / GIF'), ('lottie', 'Lottie JSON')], default='bootstrap', max_length=20)),
                ('icono_bootstrap', models.CharField(blank=True, help_text='Ejemplo: bi-capsule, bi-hospital, bi-bank, bi-shield-fill', max_length=80)),
                ('icono_archivo', models.FileField(blank=True, help_text='Sube SVG, PNG, WebP, GIF o JSON Lottie si no usarás Bootstrap Icons.', upload_to='servicios_turista/categorias/iconos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de servicio útil',
                'verbose_name_plural': 'Categorías de servicios útiles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioTurista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('tipo_atencion', models.CharField(choices=[('presencial', 'Presencial'), ('telefonica', 'Telefónica'), ('virtual', 'Virtual'), ('mixta', 'Mixta')], default='presencial', max_length=20)),
                ('disponibilidad', models.CharField(choices=[('horario', 'Horario específico'), ('veinticuatro_horas', '24 horas'), ('emergencia', 'Emergencia'), ('consultar', 'Consultar')], default='consultar', max_length=30)),
                ('horario_atencion', models.CharField(blank=True, help_text='Ejemplo: Lunes a domingo: 8:00 a. m. - 10:00 p. m. o Atención 24 horas.', max_length=180)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('recomendaciones', models.TextField(blank=True, help_text='Consejos para el turista: llevar DNI, confirmar horario, acudir en emergencia, etc.')),
                ('notas', models.TextField(blank=True, help_text='Información adicional interna o pública.')),
                ('imagen_principal', models.ImageField(blank=True, upload_to='servicios_turista/principales/')),
                ('texto_alt_imagen', models.CharField(blank=True, max_length=180)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_principales', to='servicios_turista.categoriaservicioturista', verbose_name='Categoría principal')),
                ('categorias_secundarias', models.ManyToManyField(blank=True, related_name='servicios_secundarios', to='servicios_turista.categoriaservicioturista', verbose_name='Categorías secundarias')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_turista', to='ubicaciones.distrito')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_turista', to='ubicaciones.localidad')),
            ],
            options={
                'verbose_name': 'Servicio útil para turista',
                'verbose_name_plural': 'Servicios útiles para turistas',
                'ordering': ['categoria_principal__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenServicioTurista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='servicios_turista/galeria/')),
                ('titulo', models.CharField(blank=True, max_length=160)),
                ('texto_alt', models.CharField(blank=True, max_length=180)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='servicios_turista.servicioturista')),
            ],
            options={
                'verbose_name': 'Imagen de servicio útil',
                'verbose_name_plural': 'Imágenes de servicios útiles',
                'ordering': ['servicio__nombre', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactoServicioTurista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contacto', models.CharField(choices=[('telefono', 'Teléfono'), ('celular', 'Celular'), ('whatsapp', 'WhatsApp'), ('correo', 'Correo'), ('emergencia', 'Emergencia'), ('informes', 'Informes'), ('atencion_cliente', 'Atención al cliente'), ('administracion', 'Administración'), ('otro', 'Otro')], max_length=30)),
                ('etiqueta', models.CharField(blank=True, help_text='Ejemplo: Central, Emergencias, Informes, Atención al cliente.', max_length=80)),
                ('valor', models.CharField(help_text='Número, correo o dato de contacto.', max_length=120)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='servicios_turista.servicioturista')),
            ],
            options={
                'verbose_name': 'Contacto de servicio útil',
                'verbose_name_plural': 'Contactos de servicios útiles',
                'ordering': ['servicio__nombre', 'orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='servicioturista',
            constraint=models.UniqueConstraint(fields=('distrito', 'nombre'), name='unique_servicio_turista_nombre_distrito'),
        ),
        migrations.AddConstraint(
            model_name='contactoservicioturista',
            constraint=models.UniqueConstraint(fields=('servicio', 'valor'), name='unique_contacto_servicio_turista_valor'),
        ),
        migrations.AddConstraint(
            model_name='contactoservicioturista',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('servicio', 'tipo_contacto'), name='unique_contacto_principal_tipo_servicio_turista'),
        ),
    ]
