# Generated by Django 5.2.13 on 2026-05-05 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMovilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_icono', models.CharField(choices=[('bootstrap', 'Bootstrap Icon'), ('imagen', 'Imagen / SVG / GIF'), ('lottie', 'Lottie JSON')], default='bootstrap', max_length=20)),
                ('icono_bootstrap', models.CharField(blank=True, help_text='Ejemplo: bi-car-front-fill, bi-bus-front-fill, bi-signpost-2-fill', max_length=80)),
                ('icono_archivo', models.FileField(blank=True, help_text='Sube SVG, PNG, WebP, GIF o JSON Lottie si no usarás Bootstrap Icons.', upload_to='movilidad/categorias/iconos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de movilidad',
                'verbose_name_plural': 'Categorías de movilidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioMovilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_icono', models.CharField(choices=[('bootstrap', 'Bootstrap Icon'), ('imagen', 'Imagen / SVG / GIF'), ('lottie', 'Lottie JSON')], default='bootstrap', max_length=20)),
                ('icono_bootstrap', models.CharField(blank=True, help_text='Ejemplo: bi-whatsapp, bi-credit-card-fill, bi-suitcase-fill', max_length=80)),
                ('icono_archivo', models.FileField(blank=True, help_text='Sube SVG, PNG, WebP, GIF o JSON Lottie si no usarás Bootstrap Icons.', upload_to='movilidad/servicios/iconos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio de movilidad',
                'verbose_name_plural': 'Servicios de movilidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OperadorMovilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operador', models.CharField(choices=[('taxi', 'Taxi'), ('taxi_turistico', 'Taxi turístico'), ('transporte_publico', 'Transporte público'), ('colectivo', 'Colectivo'), ('bus', 'Bus / empresa de transporte'), ('movilidad_privada', 'Movilidad privada'), ('agencia', 'Agencia / operador turístico'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('nombre', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('imagen_principal', models.ImageField(blank=True, upload_to='movilidad/operadores/principales/')),
                ('texto_alt_imagen', models.CharField(blank=True, max_length=180)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operadores_movilidad', to='ubicaciones.distrito')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores_movilidad', to='ubicaciones.localidad')),
                ('servicios', models.ManyToManyField(blank=True, related_name='operadores', to='movilidad.serviciomovilidad')),
            ],
            options={
                'verbose_name': 'Operador de movilidad',
                'verbose_name_plural': 'Operadores de movilidad',
                'ordering': ['tipo_operador', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RutaMovilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Plaza de Armas a Kotosh', max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('origen_texto', models.CharField(blank=True, help_text='Ejemplo: Plaza de Armas, Terminal terrestre, Centro de Huánuco.', max_length=180)),
                ('destino_texto', models.CharField(blank=True, help_text='Ejemplo: Kotosh, Cueva de las Lechuzas, Huánuco Pampa.', max_length=180)),
                ('punto_partida', models.CharField(blank=True, help_text='Dónde tomar la movilidad o referencia de inicio.', max_length=255)),
                ('punto_llegada', models.CharField(blank=True, help_text='Referencia del punto de llegada.', max_length=255)),
                ('indicaciones', models.TextField(blank=True, help_text='Explicación práctica de cómo llegar.')),
                ('duracion_estimada', models.CharField(blank=True, help_text='Ejemplo: 10 minutos, 30 minutos, 2 horas.', max_length=120)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distancia aproximada en kilómetros.', max_digits=7, null=True)),
                ('frecuencia', models.CharField(blank=True, help_text='Ejemplo: cada 10 minutos, según disponibilidad, previa reserva.', max_length=160)),
                ('horario_referencial', models.CharField(blank=True, help_text='Ejemplo: Lunes a domingo, 6:00 a. m. - 8:00 p. m.', max_length=180)),
                ('tipo_costo', models.CharField(choices=[('gratis', 'Gratis'), ('pagado', 'Pagado'), ('consultar', 'Consultar')], default='consultar', max_length=20)),
                ('precio_desde', models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa mínima referencial en soles.', max_digits=8, null=True, verbose_name='Precio desde')),
                ('precio_hasta', models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa máxima referencial en soles.', max_digits=8, null=True, verbose_name='Precio hasta')),
                ('dificultad', models.CharField(choices=[('no_aplica', 'No aplica'), ('facil', 'Fácil'), ('moderada', 'Moderada'), ('dificil', 'Difícil')], default='no_aplica', max_length=20)),
                ('recomendaciones', models.TextField(blank=True, help_text='Consejos para el turista: negociar tarifa, evitar horarios inseguros, llevar efectivo, etc.')),
                ('advertencias', models.TextField(blank=True, help_text='Alertas o precauciones importantes.')),
                ('imagen_principal', models.ImageField(blank=True, upload_to='movilidad/rutas/principales/')),
                ('texto_alt_imagen', models.CharField(blank=True, max_length=180)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_principales', to='movilidad.categoriamovilidad', verbose_name='Categoría principal')),
                ('categorias_secundarias', models.ManyToManyField(blank=True, related_name='rutas_secundarias', to='movilidad.categoriamovilidad', verbose_name='Categorías secundarias')),
                ('destino_distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rutas_destino_movilidad', to='ubicaciones.distrito')),
                ('destino_localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_destino_movilidad', to='ubicaciones.localidad')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='movilidad.operadormovilidad', verbose_name='Operador asociado')),
                ('origen_distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen_movilidad', to='ubicaciones.distrito')),
                ('origen_localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_origen_movilidad', to='ubicaciones.localidad')),
                ('servicios', models.ManyToManyField(blank=True, related_name='rutas', to='movilidad.serviciomovilidad', verbose_name='Servicios / facilidades')),
            ],
            options={
                'verbose_name': 'Ruta de movilidad',
                'verbose_name_plural': 'Rutas de movilidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenRutaMovilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='movilidad/rutas/galeria/')),
                ('titulo', models.CharField(blank=True, max_length=160)),
                ('texto_alt', models.CharField(blank=True, max_length=180)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='movilidad.rutamovilidad')),
            ],
            options={
                'verbose_name': 'Imagen de ruta de movilidad',
                'verbose_name_plural': 'Imágenes de rutas de movilidad',
                'ordering': ['ruta__nombre', 'orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rutamovilidad',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_ruta_movilidad_nombre'),
        ),
        migrations.AddConstraint(
            model_name='operadormovilidad',
            constraint=models.UniqueConstraint(fields=('distrito', 'nombre'), name='unique_operador_movilidad_nombre_distrito'),
        ),
    ]
